# Generated by Django 3.2.8 on 2022-09-02 16:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=1024, unique=True)),
                ('description', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('views', models.IntegerField(blank=True, default=0, editable=False)),
                ('genre', models.CharField(blank=True, max_length=256)),
            ],
        ),
    ]
