# Generated by Django 3.2.8 on 2022-09-02 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('novel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribeNovelsID', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='novel',
            name='userID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='novelsID', to=settings.AUTH_USER_MODEL),
        ),
    ]
