# Generated by Django 4.1 on 2022-08-31 06:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('novel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=1024)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('novelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chaptersID', to='novel.novel')),
            ],
        ),
    ]
